### ISSUE TITLE
otellogr emits nil context causing panic in exporters

### ISSUE THREAD

**Issue by gregoryfranklin** [open-telemetry/opentelemetry-go-contrib#6509]
### Description
By default, otellogr emits logs with a nil context - this causes exporters that do not support nil contexts to panic.

This happens because it uses a context that is never initialised
```
func NewLogSink(name string, options ...Option) *LogSink {
	return &LogSink{
		// does not initialise ctx
	}
}

type LogSink struct {
	ctx           context.Context
}

func (l *LogSink) Info(level int, msg string, keysAndValues ...any) {
	ctx, attr := convertKVs(l.ctx, keysAndValues...)

	l.logger.Emit(ctx, record)  // emits nil context
}
```

### Environment
- `go.opentelemetry.io/contrib/bridges/otellogr v0.8.0`

### Steps To Reproduce

Run the following code:
```
package main

import (
	"github.com/go-logr/logr"
	"go.opentelemetry.io/contrib/bridges/otellogr"
	"go.opentelemetry.io/otel/exporters/stdout/stdoutlog"
	"go.opentelemetry.io/otel/sdk/log"
)

func main() {
	exporter, _ := stdoutlog.New()
	processor := log.NewSimpleProcessor(exporter)
	provider := log.NewLoggerProvider(log.WithProcessor(processor))
	sink := otellogr.NewLogSink("example", otellogr.WithLoggerProvider(provider))
	logger := logr.New(sink)
	logger.Info("hello")
}
```
Results in
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x570653]

goroutine 1 [running]:
go.opentelemetry.io/otel/exporters/stdout/stdoutlog.(*Exporter).Export(0xc000016250, {0x0, 0x0}, {0xc0001284e0?, 0x0?, 0x0?})
	/tmp/.cache/go/pkg/mod/go.opentelemetry.io/otel/exporters/stdout/stdoutlog@v0.9.0/exporter.go:49 +0xf3
go.opentelemetry.io/otel/sdk/log.(*SimpleProcessor).OnEmit(0xc000070180, {0x0, 0x0}, 0xc000128340)
	/tmp/.cache/go/pkg/mod/go.opentelemetry.io/otel/sdk/log@v0.9.0/simple.go:58 +0x1ad
go.opentelemetry.io/otel/sdk/log.(*logger).Emit(_, {_, _}, {{}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...})
	/tmp/.cache/go/pkg/mod/go.opentelemetry.io/otel/sdk/log@v0.9.0/logger.go:40 +0x162
go.opentelemetry.io/contrib/bridges/otellogr.(*LogSink).Info(0xc00013e100, 0x5aae00?, {0x5cb744?, 0x623c60?}, {0x0, 0x0, 0x0})
	/tmp/.cache/go/pkg/mod/go.opentelemetry.io/contrib/bridges/otellogr@v0.8.0/logsink.go:238 +0x173
github.com/go-logr/logr.Logger.Info({{0x625428?, 0xc00013e100?}, 0xc000145f20?}, {0x5cb744, 0x5}, {0x0, 0x0, 0x0})
	/tmp/.cache/go/pkg/mod/github.com/go-logr/logr@v1.4.2/logr.go:280 +0xf3
main.main()
	/tmp/otellogr/main.go:16 +0x1ad
```
### Expected behavior
Using otellogr should not cause panics.

### Workaround
Its possible to work around this problem by passing a context via WithValues
```
sink := otellogr.NewLogSink(
	"example",
	otellogr.WithLoggerProvider(provider),
).WithValues("ctx", context.Background()),
```

**Comment by dmathieu** [comment]
cc @scorpionknifes @pellared as code owners.

**Comment by pellared** [comment]
From https://pkg.go.dev/context:

> Do not pass a nil [Context](https://pkg.go.dev/context#Context), even if a function permits it.

Similar comment here: https://github.com/open-telemetry/opentelemetry-go/issues/5161#issuecomment-2039948012

**Comment by flc1125** [comment]
Because there is no default `ctx` set here. 

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/13b1cc54589656c44ff173dc8f761a566871553e/bridges/otellogr/logsink.go#L173-L179

--- 

In addition, the `ctx` here can be directly used as `l.ctx` without having to define otherwise.

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/13b1cc54589656c44ff173dc8f761a566871553e/bridges/otellogr/logsink.go#L204-L206

**Comment by dmathieu** [comment]
If the context is mandatory, should we require it as a mandatory parameter?
Something like:

```golang
otellogr.NewLogSink(ctx, "example", otellogr.WithLoggerProvider(provider))
```

**Comment by flc1125** [comment]
I prefer to default to `context.Background()` and add a customizable `WithContext` method.

```go
otellogr.NewLogSink("example", otellogr.WithLoggerProvider(provider), otelogr.WithContext(ctx))
```

**Comment by flc1125** [comment]
I found some information, but I'm not sure if this discussion applies.

https://github.com/go-logr/logr/issues/234#issuecomment-1830482832

**Comment by flc1125** [comment]
If there is no one to deal with this problem, I can help deal with it.

**Comment by scorpionknifes** [comment]
I'm not certain what's the best way forward here.

I would prefer returning a context.Background() instead of init it with a default context. As defaulting it with a context may incentivise users to pass in a context from a trace that won't be related to the log line that does not have ctx passed in.

**Comment by flc1125** [comment]
I will handle it as follows. Do you have any good suggestions?

- I will set the default `ctx` value to `context.Background()`
- To facilitate the use of a custom `ctx`, I will add a `WithContext(ctx)` method to implement it;
- To facilitate the context association for tracing, I will add a `WithContext(ctx)` method in `*LogSink` to pass in and return a new `*LogSink` instance;
